first_aid_response_task:
  description: >
    Respond to user query with actionable first aid advice. Ensure safety, clarity, and relevance to the user's emergency.
    Use the `youtube_channel_search_tool` tool to search for a reliable YouTube video demonstrating suggested maneuvers or advice.

    Your final answer must include a well-organized, step-by-step guide that prioritizes immediate actions and user safety. If applicable, include a link to a YouTube video from trusted channels using the `youtube_channel_search_tool`. Avoid referencing missing links if no suitable video is found. Use the `youtube_channel_search_tool` by passing as an argument a list of **English** keywords related to the user query. For example: 'bee sting'.
    This is the: {query}
  expected_output: >
    A well-structured, step-by-step guide tailored to the user's query, including:
    - **A clear and concise description of the required actions**: Ensure the explanation is easy to follow and actionable for non-experts.
    - **[Optional] A relevant YouTube video link**: If a suitable video is found using the `youtube_channel_search_tool`, include the link in your response. If no video is available, omit the link entirely without mentioning its absence.
  tools: []
  agent: first_aid_chatbot
