first_aid_response_task:
  description: >
    Respond to user query with actionable first aid advice. Ensure safety, clarity, and relevance to the user's emergency.
    Use the following tools to gather reliable and accurate information:
    1. `web_rag_personaltrainer_tool`: Search for relevant first aid advice on the "My Personal Trainer" website.
    2. `web_rag_msdmanuals_tool`: Search for relevant first aid advice on the "MSD Manuals" website.
    3. `youtube_channel_search_tool`: Search for reliable YouTube videos demonstrating suggested maneuvers or advice.

    Your final answer must include a well-organized, step-by-step guide that prioritizes immediate actions and user safety. If applicable, include links to YouTube videos from trusted channels using the `youtube_channel_search_tool`. Avoid referencing missing links if no suitable video is found.
    This is the: {query}
  expected_output: >
    A step-by-step guide tailored to the user's query, including:
    - A clear description of the required actions.
    - [Optional] Include some reliable YouTube video links from compliant YouTube channels that demonstrates any suggested maneuver or advice related to the user query. Use the `youtube_tool` by passing as an argument a list of English keywords related to the user query. For example: 'bee sting'. If no suitable video is found, omit the link entirely and do not mention its absence in the response.
  tools: []
  agent: first_aid_chatbot
